development:
  dapter: redis
  url: redis://jery-redis.redis.cache.windows.net:6380/0
  channel_prefix: railstasks_production

test:
  adapter: redis
  url: redis://jery-redis.redis.cache.windows.net:6380/0
  channel_prefix: railstasks_production

production:
  adapter: redis
  url: redis://jery-redis.redis.cache.windows.net:6380/0
  channel_prefix: railstasks_production
